spring:
   application:
       name: nacos-consumer-feign
   cloud:
          nacos:
              discovery:
                 server-addr:  127.0.0.1:8848
          sentinel:
            transport:
              port: 8720
              dashboard: localhost:8090



server:
   port: 9096
management:
   endpoints:
      web:
         exposure:
            include: "*"
feign:
   sentinel:
      enabled: true

